[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.23"

remappings = [
    "@aave/core-v3/=lib/aave-v3-core/",
    "aave-v3-periphery/=lib/aave-v3-periphery/",
    "@aave-v3-origin/=lib/aave-v3-origin/",
    "@compound-protocol=lib/compound-protocol/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
    "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config